name: ISPW sync workflow on Linux
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-git-ispw-sync:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux]
    # if need this 
    env:
      Linux_Topaz_Location: '/opt/Compuware/Topaz CLI'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # sync step 2
      - name: Sync step
        uses: bmc-compuware/ispw-sync-local@ZENG-226910
        id: sync-local
        with:
          host: 'cw09.compuware.com'
          port: 47623
          uid: 'ISPWTPZ'
          pass: ${{ secrets.ISPW_USER1_PWD }}
          runtimeConfiguration: 'TPZP'
          stream: 'PLAY'
          application: 'PLAY'
          checkoutLevel: 'DEV1'
          gitUid: 'vbugale'
          gitToken: ${{ secrets.GITHUB_TOKEN }}
          unixTopazPath: ${{ env.Linux_Topaz_Location }}
          showEnv: false
